### ISSUE TITLE
Insufficient error reporting for inconsistent language sets

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#10]
When faced with two input data files with non-equal language sets, `beastling` dies during the process with an error message that might not be easily comprehensible for the uninitiated user.

```
Traceback (most recent call last):
  File "/home/gereon/python/pkg_beastling/bin/beastling", line 34, in <module>
    main()
  File "/home/gereon/python/pkg_beastling/bin/beastling", line 24, in main
    xml = beastling.beastxml.BeastXml(config)
  File "/home/gereon/python/beastling/beastxml.py", line 32, in __init__
    self.build_xml()
  File "/home/gereon/python/beastling/beastxml.py", line 115, in build_xml
    model.add_likelihood(self.likelihood)
  File "/home/gereon/python/beastling/models/basemodel.py", line 194, in add_likelihood
    self.add_data(distribution, trait, traitname)
  File "/home/gereon/python/beastling/models/covarion.py", line 44, in add_data
    traitrange = sorted(list(set(self.data[lang][trait] for lang in self.config.languages)))
  File "/home/gereon/python/beastling/models/covarion.py", line 44, in <genexpr>
    traitrange = sorted(list(set(self.data[lang][trait] for lang in self.config.languages)))
KeyError: u'Afrikaans'
```

Instead, I think the default behaviour should be to early on test the overlap of the language sets, and – depending on a choice made in `[language]`, I guess – incompatibility should lead to either an error being raised, or the union or intersection of available values being taken.

**Comment by lmaurits** [comment]
This should now be fixed by your commit which I have merged.  I like your solution of giving a choice between taking the union or intersection, I probably would have just hard-coded a union.
