### ISSUE TITLE
Frequency in bsvs add_sitemodel is not robust

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#122]
There are two issues with the frequencies in BSVS.

One, estimating frequencies can apparently be 0 in norm, I'll hunt that down and try to solve it:
```
$ beastling variable.ini plus_typology.ini
Error encountered while building BeastXML object:
Traceback (most recent call last):
  File "/home/gereon/beasties/beastling/beastling/cli.py", line 116, in do_generate
    xml = BeastXml(config)
  File "/home/gereon/beasties/beastling/beastling/beastxml.py", line 40, in __init__
    self.build_xml()
  File "/home/gereon/beasties/beastling/beastling/beastxml.py", line 61, in build_xml
    self.add_run()
  File "/home/gereon/beasties/beastling/beastling/beastxml.py", line 124, in add_run
    self.add_distributions()
  File "/home/gereon/beasties/beastling/beastling/beastxml.py", line 186, in add_distributions
    self.add_likelihood()
  File "/home/gereon/beasties/beastling/beastling/beastxml.py", line 317, in add_likelihood
    model.add_likelihood(self.likelihood)
  File "/home/gereon/beasties/beastling/beastling/models/basemodel.py", line 288, in add_likelihood
    self.add_sitemodel(distribution, f, fname)
  File "/home/gereon/beasties/beastling/beastling/models/bsvs.py", line 108, in add_sitemodel
    freqs = [f/norm for f in freqs]
  File "/home/gereon/beasties/beastling/beastling/models/bsvs.py", line 108, in <listcomp>
    freqs = [f/norm for f in freqs]
ZeroDivisionError: float division by zero
```
Two, typos in the frequency specification (note the unnecessary quotation marks!) lead to unhelpful errors, that requires just another `else` term:
```
$ echo 'frequencies = "uniform"' >> plus_typology.ini
$ beastling variable.ini plus_typology.ini
Error encountered while building BeastXML object:
Traceback (most recent call last):
  File "/home/gereon/beasties/beastling/beastling/cli.py", line 116, in do_generate
    xml = BeastXml(config)
  File "/home/gereon/beasties/beastling/beastling/beastxml.py", line 40, in __init__
    self.build_xml()
  File "/home/gereon/beasties/beastling/beastling/beastxml.py", line 61, in build_xml
    self.add_run()
  File "/home/gereon/beasties/beastling/beastling/beastxml.py", line 124, in add_run
    self.add_distributions()
  File "/home/gereon/beasties/beastling/beastling/beastxml.py", line 186, in add_distributions
    self.add_likelihood()
  File "/home/gereon/beasties/beastling/beastling/beastxml.py", line 317, in add_likelihood
    model.add_likelihood(self.likelihood)
  File "/home/gereon/beasties/beastling/beastling/models/basemodel.py", line 288, in add_likelihood
    self.add_sitemodel(distribution, f, fname)
  File "/home/gereon/beasties/beastling/beastling/models/bsvs.py", line 117, in add_sitemodel
    "name":"frequencies"}).text=freq_string
UnboundLocalError: local variable 'freq_string' referenced before assignment
```

**Comment by Anaphory** [comment]
Okay, the first error comes from the following fact:

My Values are floating point numbers, not integers (for some reasons lying in how we deal with data and that `pandas` is involved).

So, `self.counts[feature]` is something like `{'0.0': 7, '1.0': 6, '3.0': 3}`, with `self.valuecounts[feature] == 3`. But of course its `get(str(v), 0)` gives `0` every time, because `1`, `2` and `3` are not in that dictionary!

Is there reason to assume our Values should be strings containing a range of integers starting with 1?
