### ISSUE TITLE
Non-existing languages file yields unhelpful traceback

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#76]
I have just spent far too much time digging through beastling code because the file speficified in

```
[languages]
languages=this_file
```

did not exist. Instead of noticing that my language list contains only one element and warning me about it, or even just notifying me that the resulting language list is empty, beastling dies with

```
Traceback (most recent call last):
  File "/home/gereon/python/beastling/cli.py", line 91, in do_generate
    config.process()
  File "/home/gereon/python/beastling/configuration.py", line 357, in process
    self.instantiate_models()
  File "/home/gereon/python/beastling/configuration.py", line 546, in instantiate_models
    model = UserClass(config, self)
  File "/home/gereon/wordorderuniversals/beastling_correlated.py", line 30, in __init__
    BaseModel.__init__(self, model_config, global_config)
  File "/home/gereon/python/beastling/models/basemodel.py", line 38, in __init__
    self.process()
  File "/home/gereon/python/beastling/models/basemodel.py", line 70, in process
    self.remove_unwanted_features()
  File "/home/gereon/python/beastling/models/basemodel.py", line 178, in remove_unwanted_features
    raise ValueError("No features specified for model %s!" % self.name)
ValueError: No features specified for model wordorder!
```

because `basemodel.BaseModel.apply_language_filter()` does not notice when it reduces the language list to nothing.

**Comment by lmaurits** [comment]
Yep, I've been bitten by this before myself.  I'll try to get a fix for this together today.

**Comment by lmaurits** [comment]
Okay, finally got around to handling this!  If the value of `languages` has length 1, even after attempting to treat it as a file, then a warning message will be emitted if you have `--verbose` on.  Further, if `BaseModel.apply_language_filter()` removes _all_ languages from the dataset, it will throw an exception "Language filters leave nothing in the dataset for model foo!".  This should make it pretty clear what's happening in this scenario.
