### ISSUE TITLE
Beastling ignores file_format specification

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#82]
I just fed a malformed (`Feature ID` instead of `Feature_ID`) `cldf` csv file to beastling, specifying `file_format=cldf`. Instead complaining about the `Feature_ID` column missing, it parsed it as `beastling` csv, and complained about a duplicate language name.

Turns out that `datareaders.load_data` gets the `file_format` passed, before proceeding to ignore it.

**Comment by lmaurits** [comment]
When you get a chance if you can confirm that your malformed file is still correctly rejected with the latest code, that would be great.

**Comment by Anaphory** [comment]
The file is correctly rejected, although _technically_ the missing key is not `Parameter_ID`, but the equally permitted `Feature_ID`.

```
Error encountered while parsing configuration file:
Traceback (most recent call last):
  File "/home/gereon/python/beastling/cli.py", line 102, in do_generate
    config.process()
  File "/home/gereon/python/beastling/configuration.py", line 372, in process
    self.instantiate_models()
  File "/home/gereon/python/beastling/configuration.py", line 745, in instantiate_models
    model = covarion.CovarionModel(config, self)
  File "/home/gereon/python/beastling/models/binary.py", line 10, in __init__
    BaseModel.__init__(self, model_config, global_config)
  File "/home/gereon/python/beastling/models/basemodel.py", line 38, in __init__
    self.data = load_data(self.data_filename, file_format=model_config.get("file_format",None), lang_column=model_config.get("language_column",None))
  File "/home/gereon/python/beastling/fileio/datareaders.py", line 48, in load_data
    data = load_cldf_data(reader)
  File "/home/gereon/python/beastling/fileio/datareaders.py", line 86, in load_cldf_data
    data[lang][row[feature_column]] = row["Value"]
KeyError: 'Parameter_ID'
```

**Comment by lmaurits** [comment]
Could you kindly `pull` and test this one last time?  You should now get a technically correct error message.

**Comment by lmaurits** [comment]
This is now the last remaining non-documentation issue tagged with the 1.2.0 milestone.

**Comment by Anaphory** [comment]
Very good!
