### ISSUE TITLE
Additional columns in CLDF are not ignored

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#95]
When trying to figure out how beastling behaves when supplied with ambiguous information on the language column in CLDF data files (trying to see whether #83 is resolved – I tried to specify `Language` as the language column in the config file, but to also have a `Language_ID` column as mandated by CLDF) I got an unexpected exception raised.

```
beastling reconstruct.ini
Error encountered while parsing configuration file:
Traceback (most recent call last):
  File "/home/gereon/python/beastling/cli.py", line 102, in do_generate
    config.process()
  File "/home/gereon/python/beastling/configuration.py", line 372, in process
    self.instantiate_models()
  File "/home/gereon/python/beastling/configuration.py", line 745, in instantiate_models
    model = covarion.CovarionModel(config, self)
  File "/home/gereon/python/beastling/models/binary.py", line 12, in __init__
    self.compute_feature_properties()
  File "/home/gereon/python/beastling/models/basemodel.py", line 144, in compute_feature_properties
    if all([v.isdigit() for v in unique_values]):
  File "/home/gereon/python/beastling/models/basemodel.py", line 144, in <listcomp>
    if all([v.isdigit() for v in unique_values]):
AttributeError: 'NoneType' object has no attribute 'isdigit'
```

This is not specific to specifying a language column, as the attached files show.
[issue_example.zip](https://github.com/lmaurits/BEASTling/files/513473/issue_example.zip)

**Comment by Anaphory** [comment]
Maybe I should remark that I duplicated the language column, which for some reason is empty for part of the file. I'll test whether the error persists for non-empty unimportant columns.

**Comment by Anaphory** [comment]
If the superfluous column is not empty, this issue does not exist, as proven by the fact that the resulting xml files match.
[no_empty_ignored_cells.zip](https://github.com/lmaurits/BEASTling/files/513586/no_empty_ignored_cells.zip)

But this points to a deeper issue, namely that the data reader tries to parse all columns, even those that don't matter.

**Comment by Anaphory** [comment]
Hm.

`binary.py`, l. 12, contains a call to `self.compute_feature_properties()`. The corresponding `BaseModel.__init__` does not call this method there (but I think it's called somewhere nonetheless), and commenting it out did not break my example zipped above.

Now to put empty cells back in.

**Comment by Anaphory** [comment]
It does indeed fail again, inside `compute_feature_properties()`, this time called from `process()`:

```
$ beastling reconstruct.ini 
Error encountered while parsing configuration file:
Traceback (most recent call last):
  File "/home/gereon/python/beastling/cli.py", line 102, in do_generate
    config.process()
  File "/home/gereon/python/beastling/configuration.py", line 374, in process
    self.process_models()
  File "/home/gereon/python/beastling/configuration.py", line 773, in process_models
    model.process()
  File "/home/gereon/python/beastling/models/covarion.py", line 9, in process
    BinaryModel.process(self)
  File "/home/gereon/python/beastling/models/basemodel.py", line 66, in process
    self.compute_feature_properties()
  File "/home/gereon/python/beastling/models/basemodel.py", line 144, in compute_feature_properties
    if all([v.isdigit() for v in unique_values]):
  File "/home/gereon/python/beastling/models/basemodel.py", line 144, in <listcomp>
    if all([v.isdigit() for v in unique_values]):
AttributeError: 'NoneType' object has no attribute 'isdigit'
```

**Comment by Anaphory** [comment]
I blame my own incompetence: I did not cleanly double the Language column.
